
class Conection():
    api_id = 2684651
    api_hash = '69ebc6695f7ab2ac9bae9c2940ab7b05'
    phone = '+5574981423804'
    id_groups = -100+'1729353083'

    Paridades = ["AUDCAD-OTC","EURJPY-OTC","EURGBP-OTC","EURUSD-OTC","GBPJPY-OTC","GBPUSD-OTC","USDJPY-OTC","USDCHF-OTC","NZDUSD-OTC","AUDCAD(OTC)","EURJPY(OTC)","EURGBP(OTC)","EURUSD(OTC)","GBPJPY(OTC)","GBPUSD(OTC)","USDJPY(OTC)","USDCHF(OTC)","NZDUSD(OTC)",  "AUDCAD_otc", "AUDCHF_otc", "AUDJPY_otc", "AUDUSD_otc", "CADJPY_otc", "EURCHF_otc", "EURGBP_otc", "EURJPY_otc", "EURUSD_otc","GBPAUD_otc", "GBPJPY_otc", "NZDJPY_otc", "NZDUSD_otc", "UKBrent_otc", "USCrude_otc", "USDCAD_otc", "USDCHF_otc", "USDJPY_otc", "XAGUSD_otc", "XAUUSD_otc","AUDCAD","AUDCHF","AUDJPY","AUDUSD","AUDNZD","CADCHF","CADJPY","EURAUD","EURCAD","EURGBP","EURJPY","EURUSD","EURNZD","GBPAUD","GBPCAD","GBPCHF","GBPJPY","GBPUSD","GBPNZD","NZDUSD","USDCAD","USDCHF","USDJPY","USDNOK", "AEXEUR", "AUDCAD", "AUDCHF", "AUDJPY", "AUDNZD", "AUDUSD", "AXJAUD", "BTCUSD", "CADCHF", "CADJPY","CHIA50", "DJIUSD", "ETHUSD", "EURAUD", "EURCAD", "EURCHF", "EURGBP", "EURJPY", "EURSGD", "EURUSD", "F40EUR", "FTSGBP", "GBPAUD", "GBPCAD","GBPCHF", "GBPJPY", "GBPUSD", "GEREUR", "HSIHKD", "IBXEUR", "IT4EUR", "JPXJPY", "NDXUSD", "NZDJPY", "NZDUSD", "SPXUSD", "STXEUR", "USDCAD","USDCHF", "USDJPY", "XAGUSD", "XAUUSD"]
    Horarios = []
